/**
 * RSS Service
 * Triggers the internal RSS feed revalidation.
 * The actual feed is generated by app/api/rss/route.ts — this just
 * invalidates the Next.js cache so the next request gets a fresh feed.
 */

export interface RssResult {
  success: boolean
  error?: string
}

/**
 * Revalidate the RSS feed by hitting the internal API.
 * Safe to call from server-side code (API routes, server actions).
 */
export async function revalidateRss(baseUrl = 'https://streamb4.com'): Promise<RssResult> {
  try {
    // The RSS route is a GET endpoint; hitting it after publish is sufficient
    // because it fetches fresh data from MongoDB on every request.
    // For Next.js ISR / on-demand revalidation we call the revalidate token.
    const revalidateSecret = process.env.REVALIDATE_SECRET ?? ''

    if (revalidateSecret) {
      const res = await fetch(
        `${baseUrl}/api/revalidate?secret=${revalidateSecret}&path=/api/rss`,
        { method: 'GET' },
      )
      return { success: res.ok }
    }

    // No revalidation secret configured — the RSS route always reads live data
    return { success: true }
  } catch (err: unknown) {
    return { success: false, error: err instanceof Error ? err.message : String(err) }
  }
}
