/**
 * One-time export: copies all published posts from MongoDB into lib/data/posts.ts
 *
 * Prerequisites:
 *   1. Set MONGODB_URI in your environment (or .env.local):
 *        export MONGODB_URI="mongodb+srv://user:pass@cluster..."
 *   2. Run:  node scripts/export-posts.js
 *   3. Commit the updated lib/data/posts.ts
 *
 * No credentials are hardcoded. The script reads MONGODB_URI from the environment.
 */

require('dotenv').config({ path: '.env.local' });

const { MongoClient } = require('mongodb');
const fs = require('fs');
const path = require('path');

const URI = process.env.MONGODB_URI;
if (!URI) {
  console.error('ERROR: MONGODB_URI environment variable is not set.');
  console.error('Set it before running: export MONGODB_URI="mongodb+srv://..."');
  process.exit(1);
}

const OUT_FILE = path.join(__dirname, '../lib/data/posts.ts');

const client = new MongoClient(URI);

client.connect().then(async () => {
  const col = client.db('streamb4').collection('posts');
  const docs = await col.find({ status: 'published' })
    .sort({ isFeatured: -1, featured: -1, publishedAt: -1, createdAt: -1 })
    .toArray();

  console.log(`Fetched ${docs.length} published posts from MongoDB.`);

  // Sanitise: remove MongoDB _id and convert ObjectId/Date to plain values
  const posts = docs.map(doc => {
    const p = { ...doc };
    delete p._id;
    // Ensure all date fields are strings
    for (const key of ['publishedAt', 'updatedAt', 'createdAt']) {
      if (p[key] instanceof Date) p[key] = p[key].toISOString();
    }
    // Ensure arrays exist
    if (!Array.isArray(p.tags)) p.tags = [];
    if (!Array.isArray(p.faqs)) p.faqs = [];
    if (!Array.isArray(p.secondaryKeywords)) p.secondaryKeywords = [];
    // Ensure booleans
    p.featured = !!p.featured;
    p.isFeatured = !!p.isFeatured;
    p.isSticky = !!p.isSticky;
    p.status = 'published';
    p.views = Number(p.views) || 0;
    p.readingTime = Number(p.readingTime) || 5;
    return p;
  });

  const fileContent = `// Static blog post data — replaces MongoDB for public blog pages.
// Generated by:  node scripts/export-posts.js
// DO NOT edit by hand — re-run the script to refresh.

export interface StaticPost {
  id: string
  slug: string
  title: string
  content: string
  excerpt: string
  category: string
  tags: string[]
  author: string
  readingTime: number
  publishedAt: string
  updatedAt: string
  createdAt: string
  featuredImage: string
  seoTitle: string
  metaDescription: string
  focusKeyword: string
  secondaryKeywords: string[]
  ogTitle: string
  ogDescription: string
  ogImage: string
  faqs: { question: string; answer: string }[]
  status: 'published'
  views: number
  featured: boolean
  isFeatured: boolean
  isSticky: boolean
}

export const POSTS: StaticPost[] = ${JSON.stringify(posts, null, 2)}
`;

  fs.writeFileSync(OUT_FILE, fileContent, 'utf8');
  console.log(`Written ${posts.length} posts to ${OUT_FILE}`);
  await client.close();
}).catch(err => {
  console.error('Export failed:', err.message);
  process.exit(1);
});
